#ifndef OPEL_CONFIG_H
#define OPEL_CONFIG_H

#define OPEL_NUM_DEFAULT_RECORDING_ELE 4
#define OPEL_NUM_DEFAULT_SNAPSHOT_ELE 3
#define OPEL_NUM_DEFAULT_RAW_ELE 3

#define RAW_FORMAT_WIDTH 1280
#define RAW_FORMAT_HEIGHT 720

#define TARGET_SRC_IS_CAM 1

#define OPEL_LOG_VERBOSE 0



#endif /*OPEL_CONFIG_H*/
