# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pi/work/opel-alpha

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pi/work/opel-alpha

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/work/opel-alpha/CMakeFiles /home/pi/work/opel-alpha/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/work/opel-alpha/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cmfw_bt

# Build rule for target.
cmfw_bt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cmfw_bt
.PHONY : cmfw_bt

# fast build rule for target.
cmfw_bt/fast:
	$(MAKE) -f opel_cmfw/CMakeFiles/cmfw_bt.dir/build.make opel_cmfw/CMakeFiles/cmfw_bt.dir/build
.PHONY : cmfw_bt/fast

#=============================================================================
# Target rules for targets named cmfw_wfd

# Build rule for target.
cmfw_wfd: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cmfw_wfd
.PHONY : cmfw_wfd

# fast build rule for target.
cmfw_wfd/fast:
	$(MAKE) -f opel_cmfw/CMakeFiles/cmfw_wfd.dir/build.make opel_cmfw/CMakeFiles/cmfw_wfd.dir/build
.PHONY : cmfw_wfd/fast

#=============================================================================
# Target rules for targets named opel_cmfw

# Build rule for target.
opel_cmfw: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 opel_cmfw
.PHONY : opel_cmfw

# fast build rule for target.
opel_cmfw/fast:
	$(MAKE) -f opel_cmfw/CMakeFiles/opel_cmfw.dir/build.make opel_cmfw/CMakeFiles/opel_cmfw.dir/build
.PHONY : opel_cmfw/fast

#=============================================================================
# Target rules for targets named tmp_control

# Build rule for target.
tmp_control: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tmp_control
.PHONY : tmp_control

# fast build rule for target.
tmp_control/fast:
	$(MAKE) -f opel_cmfw/CMakeFiles/tmp_control.dir/build.make opel_cmfw/CMakeFiles/tmp_control.dir/build
.PHONY : tmp_control/fast

#=============================================================================
# Target rules for targets named DbusManager

# Build rule for target.
DbusManager: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 DbusManager
.PHONY : DbusManager

# fast build rule for target.
DbusManager/fast:
	$(MAKE) -f opel_app_manager/CMakeFiles/DbusManager.dir/build.make opel_app_manager/CMakeFiles/DbusManager.dir/build
.PHONY : DbusManager/fast

#=============================================================================
# Target rules for targets named appPackageManager

# Build rule for target.
appPackageManager: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 appPackageManager
.PHONY : appPackageManager

# fast build rule for target.
appPackageManager/fast:
	$(MAKE) -f opel_app_manager/CMakeFiles/appPackageManager.dir/build.make opel_app_manager/CMakeFiles/appPackageManager.dir/build
.PHONY : appPackageManager/fast

#=============================================================================
# Target rules for targets named appPackageRepo

# Build rule for target.
appPackageRepo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 appPackageRepo
.PHONY : appPackageRepo

# fast build rule for target.
appPackageRepo/fast:
	$(MAKE) -f opel_app_manager/CMakeFiles/appPackageRepo.dir/build.make opel_app_manager/CMakeFiles/appPackageRepo.dir/build
.PHONY : appPackageRepo/fast

#=============================================================================
# Target rules for targets named appStatusManager

# Build rule for target.
appStatusManager: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 appStatusManager
.PHONY : appStatusManager

# fast build rule for target.
appStatusManager/fast:
	$(MAKE) -f opel_app_manager/CMakeFiles/appStatusManager.dir/build.make opel_app_manager/CMakeFiles/appStatusManager.dir/build
.PHONY : appStatusManager/fast

#=============================================================================
# Target rules for targets named commManager

# Build rule for target.
commManager: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 commManager
.PHONY : commManager

# fast build rule for target.
commManager/fast:
	$(MAKE) -f opel_app_manager/CMakeFiles/commManager.dir/build.make opel_app_manager/CMakeFiles/commManager.dir/build
.PHONY : commManager/fast

#=============================================================================
# Target rules for targets named deviceManager

# Build rule for target.
deviceManager: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 deviceManager
.PHONY : deviceManager

# fast build rule for target.
deviceManager/fast:
	$(MAKE) -f opel_app_manager/CMakeFiles/deviceManager.dir/build.make opel_app_manager/CMakeFiles/deviceManager.dir/build
.PHONY : deviceManager/fast

#=============================================================================
# Target rules for targets named deviceRepo

# Build rule for target.
deviceRepo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 deviceRepo
.PHONY : deviceRepo

# fast build rule for target.
deviceRepo/fast:
	$(MAKE) -f opel_app_manager/CMakeFiles/deviceRepo.dir/build.make opel_app_manager/CMakeFiles/deviceRepo.dir/build
.PHONY : deviceRepo/fast

#=============================================================================
# Target rules for targets named globalData

# Build rule for target.
globalData: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 globalData
.PHONY : globalData

# fast build rule for target.
globalData/fast:
	$(MAKE) -f opel_app_manager/CMakeFiles/globalData.dir/build.make opel_app_manager/CMakeFiles/globalData.dir/build
.PHONY : globalData/fast

#=============================================================================
# Target rules for targets named jsonString

# Build rule for target.
jsonString: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 jsonString
.PHONY : jsonString

# fast build rule for target.
jsonString/fast:
	$(MAKE) -f opel_app_manager/CMakeFiles/jsonString.dir/build.make opel_app_manager/CMakeFiles/jsonString.dir/build
.PHONY : jsonString/fast

#=============================================================================
# Target rules for targets named miniunz

# Build rule for target.
miniunz: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 miniunz
.PHONY : miniunz

# fast build rule for target.
miniunz/fast:
	$(MAKE) -f opel_app_manager/CMakeFiles/miniunz.dir/build.make opel_app_manager/CMakeFiles/miniunz.dir/build
.PHONY : miniunz/fast

#=============================================================================
# Target rules for targets named remoteFileManager

# Build rule for target.
remoteFileManager: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 remoteFileManager
.PHONY : remoteFileManager

# fast build rule for target.
remoteFileManager/fast:
	$(MAKE) -f opel_app_manager/CMakeFiles/remoteFileManager.dir/build.make opel_app_manager/CMakeFiles/remoteFileManager.dir/build
.PHONY : remoteFileManager/fast

#=============================================================================
# Target rules for targets named repoClass

# Build rule for target.
repoClass: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 repoClass
.PHONY : repoClass

# fast build rule for target.
repoClass/fast:
	$(MAKE) -f opel_app_manager/CMakeFiles/repoClass.dir/build.make opel_app_manager/CMakeFiles/repoClass.dir/build
.PHONY : repoClass/fast

#=============================================================================
# Target rules for targets named serviceDaemonManager

# Build rule for target.
serviceDaemonManager: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 serviceDaemonManager
.PHONY : serviceDaemonManager

# fast build rule for target.
serviceDaemonManager/fast:
	$(MAKE) -f opel_app_manager/CMakeFiles/serviceDaemonManager.dir/build.make opel_app_manager/CMakeFiles/serviceDaemonManager.dir/build
.PHONY : serviceDaemonManager/fast

#=============================================================================
# Target rules for targets named serviceDaemonRepo

# Build rule for target.
serviceDaemonRepo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 serviceDaemonRepo
.PHONY : serviceDaemonRepo

# fast build rule for target.
serviceDaemonRepo/fast:
	$(MAKE) -f opel_app_manager/CMakeFiles/serviceDaemonRepo.dir/build.make opel_app_manager/CMakeFiles/serviceDaemonRepo.dir/build
.PHONY : serviceDaemonRepo/fast

#=============================================================================
# Target rules for targets named sysAppManager

# Build rule for target.
sysAppManager: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sysAppManager
.PHONY : sysAppManager

# fast build rule for target.
sysAppManager/fast:
	$(MAKE) -f opel_app_manager/CMakeFiles/sysAppManager.dir/build.make opel_app_manager/CMakeFiles/sysAppManager.dir/build
.PHONY : sysAppManager/fast

#=============================================================================
# Target rules for targets named sensorManager

# Build rule for target.
sensorManager: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sensorManager
.PHONY : sensorManager

# fast build rule for target.
sensorManager/fast:
	$(MAKE) -f opel_sensor_manager/CMakeFiles/sensorManager.dir/build.make opel_sensor_manager/CMakeFiles/sensorManager.dir/build
.PHONY : sensorManager/fast

#=============================================================================
# Target rules for targets named cam_manager

# Build rule for target.
cam_manager: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cam_manager
.PHONY : cam_manager

# fast build rule for target.
cam_manager/fast:
	$(MAKE) -f opel_camfw/CMakeFiles/cam_manager.dir/build.make opel_camfw/CMakeFiles/cam_manager.dir/build
.PHONY : cam_manager/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... cmfw_bt"
	@echo "... cmfw_wfd"
	@echo "... opel_cmfw"
	@echo "... tmp_control"
	@echo "... DbusManager"
	@echo "... appPackageManager"
	@echo "... appPackageRepo"
	@echo "... appStatusManager"
	@echo "... commManager"
	@echo "... deviceManager"
	@echo "... deviceRepo"
	@echo "... globalData"
	@echo "... jsonString"
	@echo "... miniunz"
	@echo "... remoteFileManager"
	@echo "... repoClass"
	@echo "... serviceDaemonManager"
	@echo "... serviceDaemonRepo"
	@echo "... sysAppManager"
	@echo "... sensorManager"
	@echo "... cam_manager"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

