#!/bin/bash

start_daemons(){
	sudo hciconfig hci0 piscan
	${OPEL_DIR}/bin/run.sh &
	sudo ${OPEL_DIR}/bin/sensorManager &
	cd ${OPEL_DIR}/bin/appManager
	./sysAppManager
}

stop_daemons(){
	pkill -x cam_manager
	sudo pkill -x node
	pkill -x sysAppManager
	sudo pkill -x sensorManager
	${OPEL_DIR}/bin/p2p_setup.sh stop
}

export OPEL_DIR=$(pwd)
case $1 in
"start")
start_daemons
;;
"stop")
stop_daemons
;;
*)
/bin/echo $0 [start/stop]
exit 1
;;
esac
