#!/bin/bash

start_daemons(){
	export OPEL_DIR=$(pwd)
	${OPEL_DIR}/bin/p2p_setup.sh init
	${OPEL_DIR}/bin/run.sh &
	sudo ${OPEL_DIR}/bin/sensorManager &
	cd ./bin/appManager
	./sysAppManager
}

stop_daemons(){
	pkill -x cam_manager
	pkill -x node
	pkill -x sysAppManager
	sudo pkill sensorManager
}

case $1 in
"start")
start_daemons
;;
"stop")
stop_daemons
;;
*)
/bin/echo $0 [start/stop]
exit 1
;;
esac
