#ifndef OPEL_CONFIG_H
#define OPEL_CONFIG_H

#define OPEL_NUM_DEFAULT_RECORDING_ELE 4
#define OPEL_NUM_DEFAULT_SNAPSHOT_ELE 3
#define OPEL_NUM_DEFAULT_RAW_ELE 3

#define RAW_DEFAULT_BUF_SIZE 4194304

#define SHM_KEY_FOR_BUFFER 5315

#define RAW_FORMAT_WIDTH 1280
#define RAW_FORMAT_HEIGHT 720

#define TARGET_SRC_IS_CAM 1

#define OPEL_LOG_VERBOSE 0



#endif /*OPEL_CONFIG_H*/
